import React,{useMemo,useState}from'react';
import{SafeAreaView,View,Text,StyleSheet,TouchableOpacity,TextInput,ScrollView,Alert}from'react-native';
import{Ionicons}from'@expo/vector-icons';

const initial=[{id:1,title:'Food',cat:'Food',amount:-250},{id:2,title:'Bus Pass',cat:'Travel',amount:-600},{id:3,title:'Monthly Salary',cat:'Income',amount:30000},{id:4,title:'Shopping',cat:'Shopping',amount:-1200}];

export default function App(){
 const[s,setS]=useState('home'),[tx,setTx]=useState(initial),[amount,setAmount]=useState(''),[kind,setKind]=useState('Expense'),[cat,setCat]=useState('Food'),[note,setNote]=useState('');
 const income=useMemo(()=>tx.filter(x=>x.amount>0).reduce((a,x)=>a+x.amount,0),[tx]);
 const expense=useMemo(()=>tx.filter(x=>x.amount<0).reduce((a,x)=>a+Math.abs(x.amount),0),[tx]);
 const add=()=>{let n=Number(amount);if(!n)return Alert.alert('Enter a valid amount');setTx([{id:Date.now(),title:note||cat,cat,amount:kind==='Income'?n:-n},...tx]);setAmount('');setNote('');setS('home')};
 return <SafeAreaView style={st.safe}><View style={st.app}>
 {s==='home'&&<Home income={income} expense={expense} tx={tx} go={setS}/>}
 {s==='add'&&<Add amount={amount} setAmount={setAmount} kind={kind} setKind={setKind} cat={cat} setCat={setCat} note={note} setNote={setNote} add={add} back={()=>setS('home')}/>}
 {s==='history'&&<History tx={tx} back={()=>setS('home')}/>}
 {s==='summary'&&<Summary income={income} expense={expense} back={()=>setS('home')}/>}
 {s==='profile'&&<Profile back={()=>setS('home')}/>}
 {s!=='add'&&<Nav s={s} go={setS}/>}</View></SafeAreaView>
}
const Row=({x})=><View style={st.row}><View style={st.ic}><Ionicons name={x.amount>0?'arrow-down-outline':'arrow-up-outline'} size={19} color={x.amount>0?'#18794e':'#b42318'}/></View><View style={{flex:1}}><Text style={st.bold}>{x.title}</Text><Text style={st.sub}>{x.cat} • Today</Text></View><Text style={[st.bold,{color:x.amount>0?'#18794e':'#b42318'}]}>{x.amount>0?'+':'-'}₹{Math.abs(x.amount).toLocaleString('en-IN')}</Text></View>;
const Home=({income,expense,tx,go})=><ScrollView contentContainerStyle={st.pad}><View style={st.head}><View><Text style={st.kicker}>PERSONAL FINANCE</Text><Text style={st.title}>SpendWise</Text></View><Ionicons name="wallet-outline" size={31} color="#172033"/></View><View style={st.card}><Text style={st.sub}>Total Balance</Text><Text style={st.balance}>₹{(income-expense).toLocaleString('en-IN')}</Text><View style={st.two}><View><Text style={st.sub}>Income</Text><Text style={st.green}>+₹{income.toLocaleString('en-IN')}</Text></View><View><Text style={st.sub}>Expenses</Text><Text style={st.red}>-₹{expense.toLocaleString('en-IN')}</Text></View></View></View><TouchableOpacity style={st.btn} onPress={()=>go('add')}><Text style={st.btnText}>＋ Add Transaction</Text></TouchableOpacity><View style={st.head2}><Text style={st.section}>Recent Transactions</Text><TouchableOpacity onPress={()=>go('history')}><Text>View all</Text></TouchableOpacity></View>{tx.slice(0,4).map(x=><Row key={x.id} x={x}/>)}<TouchableOpacity style={st.out} onPress={()=>go('summary')}><Text style={st.bold}>◔ View Monthly Summary</Text></TouchableOpacity></ScrollView>;
const Add=({amount,setAmount,kind,setKind,cat,setCat,note,setNote,add,back})=><ScrollView contentContainerStyle={st.pad}><View style={st.head}><TouchableOpacity onPress={back}><Ionicons name="arrow-back" size={26}/></TouchableOpacity><Text style={st.title}>Add Transaction</Text><View/></View><Text style={st.lab}>Amount</Text><TextInput style={st.input} keyboardType="numeric" placeholder="₹ 0" value={amount} onChangeText={setAmount}/><Text style={st.lab}>Type</Text><View style={st.two}><TouchableOpacity style={[st.seg,kind==='Expense'&&st.active]} onPress={()=>setKind('Expense')}><Text>Expense</Text></TouchableOpacity><TouchableOpacity style={[st.seg,kind==='Income'&&st.active]} onPress={()=>setKind('Income')}><Text>Income</Text></TouchableOpacity></View><Text style={st.lab}>Category</Text><View style={st.wrap}>{['Food','Travel','Shopping','Bills','Other'].map(c=><TouchableOpacity key={c} style={[st.chip,cat===c&&st.active]} onPress={()=>setCat(c)}><Text>{c}</Text></TouchableOpacity>)}</View><Text style={st.lab}>Note</Text><TextInput style={st.input} placeholder="e.g. Lunch" value={note} onChangeText={setNote}/><TouchableOpacity style={st.btn} onPress={add}><Text style={st.btnText}>✓ Save Transaction</Text></TouchableOpacity></ScrollView>;
const History=({tx,back})=><ScrollView contentContainerStyle={st.pad}><View style={st.head}><TouchableOpacity onPress={back}><Ionicons name="arrow-back" size={26}/></TouchableOpacity><Text style={st.title}>History</Text><View/></View><TextInput style={st.input} placeholder="Search transactions"/>{tx.map(x=><Row key={x.id} x={x}/>)}</ScrollView>;
const Summary=({income,expense,back})=><ScrollView contentContainerStyle={st.pad}><View style={st.head}><TouchableOpacity onPress={back}><Ionicons name="arrow-back" size={26}/></TouchableOpacity><Text style={st.title}>Monthly Summary</Text><View/></View><View style={st.card}><Text style={st.sub}>August 2026</Text><Text style={st.balance}>₹{(income-expense).toLocaleString('en-IN')}</Text><Text style={st.sub}>Remaining balance</Text></View><View style={st.two}><View style={st.small}><Text style={st.sub}>Income</Text><Text style={st.green}>₹{income.toLocaleString('en-IN')}</Text></View><View style={st.small}><Text style={st.sub}>Expenses</Text><Text style={st.red}>₹{expense.toLocaleString('en-IN')}</Text></View></View><Text style={st.section}>Category Spending</Text><Row x={{title:'Food',cat:'Category',amount:-250}}/><Row x={{title:'Travel',cat:'Category',amount:-600}}/><Row x={{title:'Shopping',cat:'Category',amount:-1200}}/></ScrollView>;
const Profile=({back})=><View style={st.pad}><View style={st.head}><TouchableOpacity onPress={back}><Ionicons name="arrow-back" size={26}/></TouchableOpacity><Text style={st.title}>Profile</Text><View/></View><View style={st.avatar}><Ionicons name="person" size={40}/></View><Text style={st.center}>SpendWise User</Text><View style={st.setting}><Text>Monthly Budget</Text><Text>₹20,000</Text></View><View style={st.setting}><Text>Currency</Text><Text>INR (₹)</Text></View><View style={st.setting}><Text>Notifications</Text><Text>On</Text></View></View>;
const Nav=({s,go})=><View style={st.nav}>{[['home-outline','Home','home'],['receipt-outline','History','history'],['person-outline','Profile','profile']].map(([i,l,k])=><TouchableOpacity key={k} onPress={()=>go(k)} style={st.navitem}><Ionicons name={i} size={22} color={s===k?'#172033':'#98a2b3'}/><Text style={st.sub}>{l}</Text></TouchableOpacity>)}</View>;
const st=StyleSheet.create({safe:{flex:1,backgroundColor:'#f5f7fa'},app:{flex:1,maxWidth:520,width:'100%',alignSelf:'center',backgroundColor:'#fff'},pad:{padding:22,paddingBottom:105},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:22},head2:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:22},kicker:{fontSize:10,fontWeight:'800',color:'#7a8494',letterSpacing:1},title:{fontSize:26,fontWeight:'800',color:'#172033'},card:{backgroundColor:'#eef2ff',borderRadius:22,padding:22,marginBottom:14},balance:{fontSize:34,fontWeight:'800',color:'#172033',marginVertical:6},sub:{fontSize:12,color:'#7a8494'},two:{flexDirection:'row',gap:12,marginTop:10},green:{fontSize:15,fontWeight:'800',color:'#18794e'},red:{fontSize:15,fontWeight:'800',color:'#b42318'},btn:{height:54,borderRadius:15,backgroundColor:'#172033',alignItems:'center',justifyContent:'center',marginVertical:10},btnText:{color:'#fff',fontWeight:'800',fontSize:16},section:{fontSize:18,fontWeight:'800',color:'#172033',marginVertical:12},row:{flexDirection:'row',alignItems:'center',paddingVertical:13,borderBottomWidth:1,borderBottomColor:'#edf0f4'},ic:{width:42,height:42,borderRadius:13,backgroundColor:'#f5f7fa',alignItems:'center',justifyContent:'center',marginRight:12},bold:{fontSize:14,fontWeight:'700',color:'#172033'},out:{height:52,borderWidth:1,borderColor:'#d8dde6',borderRadius:14,alignItems:'center',justifyContent:'center',marginTop:18},lab:{fontWeight:'700',marginTop:10,marginBottom:8,color:'#344054'},input:{height:52,borderWidth:1,borderColor:'#d8dde6',borderRadius:14,paddingHorizontal:14,marginBottom:10},seg:{flex:1,height:44,borderRadius:11,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'#d8dde6'},active:{backgroundColor:'#eef2ff'},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:10},chip:{paddingHorizontal:14,paddingVertical:10,borderRadius:18,borderWidth:1,borderColor:'#d8dde6'},small:{flex:1,borderWidth:1,borderColor:'#e5e8ee',borderRadius:14,padding:15},avatar:{width:90,height:90,borderRadius:45,backgroundColor:'#eef2ff',alignSelf:'center',alignItems:'center',justifyContent:'center',marginTop:30},center:{textAlign:'center',fontSize:20,fontWeight:'800',marginVertical:15,color:'#172033'},setting:{flexDirection:'row',justifyContent:'space-between',paddingVertical:18,borderBottomWidth:1,borderBottomColor:'#edf0f4'},nav:{position:'absolute',bottom:0,left:0,right:0,height:78,borderTopWidth:1,borderTopColor:'#e7eaf0',backgroundColor:'#fff',flexDirection:'row',justifyContent:'space-around',paddingTop:10},navitem:{alignItems:'center'}});